### ISSUE TITLE
There are failing tests on Windows

### ISSUE THREAD

**Issue by notriddle** [blabaere/scaproust#1]
They've been failing for awhile now. https://ci.appveyor.com/project/blabaere/scaproust/build/1.0.403

**Comment by blabaere** [comment]
Hi,

Thanks for your interest and the notification. I did notice the appveyor build status when it broke last week. I'm currently refactoring the socket readiness observer system in order to implement a polling feature and some breakage on device tests is something that I expected. 

The good news is that I'm not going to ignore these broken tests. 
The bad news is:
- I don't own a Windows machine
- mio implementation and behavior is significantly different between *nix and Windows
- Investigation with println and appveyor requires time
- I won't have much spare time in the next two weeks.

So it will take time, but it will be fixed.

Regards,
Benoît

**Comment by blabaere** [comment]
@notriddle The appveyor build passes with mio 0.6.0 instead of 0.6.1 so I'll file an issue.

**Comment by blabaere** [comment]
One of the mio authors has provided an explanation of the problem and a fix idea. Applying it did fix the problem so I'll close the issue for now.
